apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logspout
spec:
  template:
    metadata:
      labels:
        name: logspout
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
      - resources:
        securityContext:
          privileged: true
        env:
        - name: ROUTE_URIS
          value: syslog+tls://logs6.papertrailapp.com:50341
        - name: SYSLOG_TAG
          value: '{{ index .Container.Config.Labels "io.kubernetes.pod.namespace" }}[{{ index .Container.Config.Labels "io.kubernetes.pod.name" }}]'
        - name: SYSLOG_HOSTNAME
          value: '{{ index .Container.Config.Labels "io.kubernetes.container.name" }}'
        image: gliderlabs/logspout
        name: logspout
        volumeMounts:
          - name: log
            mountPath: /var/run/docker.sock
      volumes:
        - name: log
          hostPath:
              path: /var/run/docker.sock
